# Generated by Django 3.2.3 on 2021-05-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_Key', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=200)),
                ('field', models.IntegerField()),
                ('data', models.IntegerField()),
            ],
        ),
    ]
